### ISSUE TITLE
rephrase/add to search bar wording

### ISSUE THREAD

**Issue by ghost** [OpenOil-UG/aleph#21]
The search bar is the point of depart for most and it seems they are following the instructions to the word - that we have provided in the search bar. The current sentence: "Search people, companies, and other entities". 

We see users looking for exactly those things, when the array is much broader. 

Possible solution: 

1) add more terms to this sentence 
2) add a random new example each time the page is visited.

**Comment by danohu** [comment]
immediate solution: "Search people, companies, countries and other entities".
later: rotate ~6 suggestions
