### ISSUE TITLE
Landing page, daily counter of new results 

### ISSUE THREAD

**Issue by ghost** [OpenOil-UG/aleph#29]
Underneath the Landing Page Headline ("over 2 million corporate documents") add a counter for new results. 

Ex. x from Canadian Corporate Filings, x from US (EDGAR), x from Australian Stock Exchange. 

1) limit to three same sources 
OR
2) limit to three sources with top number of new results.

Thanks!

**Comment by danohu** [comment]
fixed in 393cf49dac26c372eb9a9737fb8f2c25a92ebb60
