### ISSUE TITLE
Date Sorting

### ISSUE THREAD

**Issue by OpenOilUG** [OpenOil-UG/aleph#3]
The sort-date drop-down list excludes recently acquired files.

For instance, when I navigate to the US filings database today (07.04) it shows filings from yesterday: http://search.openoil.net/#/search?source=sec-edgar

However when I then take those same results and use the drop down list, the most recent file included at the top is January 29: http://search.openoil.net/#/search?source=sec-edgar&sort=date - so we know there are documents in there from Feb, March and April - but they are now lost.

**Comment by danohu** [comment]
Fixed for new documents -- but need to rerun over docs from the previous few months

**Comment by antnrueh** [comment]
Seems like the date sorting is still fairly random - see the attached (using this searchterm: http://search.openoil.net/#/search?sort=date&q=%22project%20cashflow%20negative%22~20 )
![datesorting](https://cloud.githubusercontent.com/assets/8330302/15115563/ea05e726-15ff-11e6-92a1-302ec42bf7e5.PNG)
