### ISSUE TITLE
fix search section alignment 

### ISSUE THREAD

**Issue by ghost** [OpenOil-UG/aleph#39]
x shuttleworth positioning
x create an email alert box
x leave out sign in with twitter 
x leave out sign in with email 
Or is that a/b testing? 
then i would suggest putting it under one sign in box 

![capture 2016-04-02 at 7 21 23](https://cloud.githubusercontent.com/assets/7568877/14807859/7473f0ae-0b80-11e6-95da-80df87943c25.png)

**Comment by danohu** [comment]
not relevant to new aleph
