### ISSUE TITLE
welcome email for new registrations

### ISSUE THREAD

**Issue by danohu** [OpenOil-UG/aleph#49]
requested by Johnny

**Comment by danohu** [comment]
@lucileneden -- could you write some text for the welcome email for new users? The placeholder is https://github.com/OpenOil-UG/aleph/blob/master/aleph/templates/welcome_mail.html

**Comment by lucileneden** [comment]
Notes: 

Welcome note
Account Info 
Need something extra? 

example: 

Thank you for creating an Aleph account. You can access it at https://search.openoil.net

Information on your account: 

Lucile 
lucile.neden@openoil.net 

What can you do with Aleph? 

1) research
2) ask an expert to help you define your searches aleph@openoil.net
3) create automatic email alerts for your searches to receive new corporate documents straight to your inbox.

**Comment by ghost** [comment]
![capture 2016-05-05 at 12 59 10](https://cloud.githubusercontent.com/assets/7568877/15606198/eb84a380-240a-11e6-9fe7-a13052666b32.png)

**Comment by danohu** [comment]
Thanks!

I'll drop Name, though, until we start collecting names on signup (if we do)

**Comment by ghost** [comment]
Related to https://github.com/OpenOil-UG/aleph/issues/59
Subject: Welcome to Aleph 

Thank you for creating an account with Aleph - everything extractive industries tell investors, in one place. 

Your account information:

Email: 
Password:

[seperating line]

Useful tips:

Use the "Help" tab to find interesting ways of researching with Aleph
Create an email alert for a query [link to create an email alert]
Ask an expert by emailing aleph@openoil.net

Thanks,
Aleph Team
