### ISSUE TITLE
Press Register: Pop Up

### ISSUE THREAD

**Issue by ghost** [OpenOil-UG/aleph#59]
![capture 2016-05-05 at 12 45 42](https://cloud.githubusercontent.com/assets/7568877/15605886/19472326-2409-11e6-9611-db29a5ed51b8.png)

**Comment by lucileneden** [comment]
triggers same welcome email https://github.com/OpenOil-UG/aleph/issues/49

**Comment by ghost** [comment]
Register for Aleph Alerts
