### ISSUE TITLE
Create An Email Alert: Pop Up 

### ISSUE THREAD

**Issue by ghost** [OpenOil-UG/aleph#61]
![capture 2016-05-05 at 13 21 07](https://cloud.githubusercontent.com/assets/7568877/15606684/147b022c-240e-11e6-998b-2f2424580fa0.png)

**Comment by ghost** [comment]
Set up an email alert: 

Search Query: filled in with terms in the current search (if not searching for anything please put sample search in grey as an example). 
Occurence: daily weekly 

Submit

**Comment by danohu** [comment]
change is having sample search in grey

**Comment by danohu** [comment]
@lucileneden please suggest some sample text
