### ISSUE TITLE
Press Create An Email Alert (Not signed ready to click log in): Pop Up

### ISSUE THREAD

**Issue by ghost** [OpenOil-UG/aleph#64]
First https://github.com/OpenOil-UG/aleph/issues/48 
Then sign in pop up
![capture 2016-05-05 at 13 39 34](https://cloud.githubusercontent.com/assets/7568877/15607087/7fe16202-2410-11e6-9500-a5d59ce6ecd8.png)

Then it brings you to Create An Email Alert Pop Up 
related to https://github.com/OpenOil-UG/aleph/issues/61

**Comment by danohu** [comment]
change is to send to Create An Email Alert Pop Up  after
